@host = localhost:8080

// Access a Secured API Endpoint
POST http://{{host}}/api/bank/topup HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN1c3RvbWVyIiwiZXhwIjoxNzAyMzA1MjY4fQ.Z9ImkusGXrSUSqDpfwQi_mV_xD1pchMph45fNTnihJU
content-type: application/json

{
    "balance": 100000
}

###